### ISSUE TITLE
"cargo test" fails with "android-ndk-sys only supports compiling for Android"

### ISSUE THREAD

**Issue by dmarcoux** [maplibre/maplibre-rs#108]
I'm trying to work on one of the issues labelled with `good first issue` and to ensure that my changes aren't breaking anything, I would like to run the tests, but it's failing.

## 🤔 Expected Behavior

I expect the tests to be executed when I run `cargo test`.

## 😯 Current Behavior

I forked the repository and installed the toolchain with `cargo --version > /dev/null` as seen in the [justfile](https://github.com/maplibre/maplibre-rs/blob/c3edea26e58feabab3df04b6d77ea15cfeecba4d/justfile#L27-L29). I then executed `cargo test` and it failed with the error:

```
error: android-ndk-sys only supports compiling for Android
  --> /home/johndoe/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-sys-0.2.2/src/lib.rs:22:1
   |
22 | compile_error!("android-ndk-sys only supports compiling for Android");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `ndk-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

## 🌍 Your Environment

* Desktop
    - Operating System: Linux (NixOS)
    - Display Server: Xorg

**Comment by maxammann** [comment]
I think you might uncovered an additional bug. We currently do not run the tests in the CI :see_no_evil: So maybe the tests don't even run :dagger: 

The error above happens because by default `cargo test` runs all tests in all crates in the workspace. But that won't work because at least one crate only works when the target is set to android.
So for now you can just do `cargo test -p maplibre`

**Comment by dmarcoux** [comment]
Oh, I understand now. Thank you for the explanation. Should we update the `justfile` from `cargo test` to `cargo test -p maplibre`?

**Comment by maxammann** [comment]
@dmarcoux that sounds good! hm, but we will also have tests in `maplibre-demo`, "maplibre-android", `apple`, `web` etc.

So we need some way of easily running all the tests.

**Comment by maxammann** [comment]
So I'm not sure how we should handle the ndk dependency. Any crate which includes this can no longer (easily) be used to run tests I think.

**Comment by maxammann** [comment]
@yzsolt is taking care of the unit tests right now. I'd leave this issue open as we need to see how we can handle android. We might need cross: https://github.com/cross-rs/cross
