### ISSUE TITLE
macos xcode buid project error: ld: library not found for -lmapr

### ISSUE THREAD

**Issue by snake89322** [maplibre/maplibre-rs#19]
cargo build --target aarch64-apple-darwin --lib: success
but, xcode buid error:

ld: library not found for -lmapr

so where can I found -lmapr

**Comment by maxammann** [comment]
Currently continuing to refactor this, will fix th project in this PR

**Comment by maxammann** [comment]
I finished refactoring this. You can run it on macos:

`just xcodebuild-xcframework`
`cd apple/MapLibreRs/ && swift run`
