### ISSUE TITLE
Add names to steps in Github Actions

### ISSUE THREAD

**Issue by maxammann** [maplibre/maplibre-rs#23]
Steps in the CI are currently unnamed because they reference composed steps. Add a `name:` tag to all steps.

**Comment by Tristramg** [comment]
I thought that this issue might be easy enough for me. But it seems that is actually already done.

I looked for `steps:` across the project, and excepted `- uses: actions/checkout@v3`, and a few `- uses: actions/upload-artifact@v3` all steps have a name.

Is it worth naming the few remaining artifact uploads, or did I miss-understand the issue?

**Comment by maxammann** [comment]
Yeah it could be that this was already done by me along the way. Sorry!
