### ISSUE TITLE
Demo crashes when minimizing window on Windows 10

### ISSUE THREAD

**Issue by terrorfisch** [maplibre/maplibre-rs#274]
## 🤔 Expected Behavior
The window minimizes to the taskbar and can be maximized again

## 😯 Current Behavior

Demo crashes.

```
     6: maplibre::render::resource::surface::Surface::resize
               at .\maplibre\src\render\resource\surface.rs:297
     7: maplibre::render::Renderer::resize_surface
               at .\maplibre\src\render\mod.rs:243
     8: maplibre::context::MapContext::resize
               at .\maplibre\src\context.rs:17
     9: maplibre_winit::impl$2::run::closure$0<tuple$<>,maplibre_winit::WinitEnvironment<maplibre::platform::noweb::scheduler::TokioScheduler,maplibre::platform::noweb::http_client::ReqwestHttpClient,maplibre::platform::noweb::ReqwestOffscreenKernelEnvironment,ma
               at .\maplibre-winit\src\lib.rs:121
```

Operating System: Windows 10

**Comment by maxammann** [comment]
@terrorfisch can you test this again on main on Windows? This exe here might just work on Windows :) https://github.com/maplibre/maplibre-rs/actions/runs/10104972544/artifacts/1742408563

**Comment by maxammann** [comment]
Just tested and this still happens here: https://github.com/maplibre/maplibre-rs/blob/74d76a14609fe4200d41c1f6c50791b6db5a9a75/maplibre-winit/src/lib.rs#L160
