### ISSUE TITLE
WebGL Examples not working correct in Firefox

### ISSUE THREAD

**Issue by mxzinke** [maplibre/maplibre-rs#319]
## 🤔 Expected Behavior

Shows interactive map smoothly on 75 FPS (I have a 75hz monitor).

### The default WebGL Demo:

Runs smoothly and interactive, but with 150 FPS. (Also tested with Safari, there is everything normal.)

### The WebGL /w multithreading Demo:

No errors. Tells about 75 FPS. But **nothing on screen (blank)**.

See the capture for more details:
[capture 10_26_23.json](https://github.com/user-attachments/files/17339893/capture.10_26_23.json)

## 🌍 Your Environment

Display: 75hz
System: MacOS Sequoia 15.0.1 (on M2)

Web
    - Browser: Firefox
    - Version: 131.0

**Comment by maxammann** [comment]
Interesting :O I feel like the 150fps are a bug of wgpu or winit. 

The other thing I'll look into :)


Do you happen to be at EuroRust?

**Comment by mxzinke** [comment]
Looking forward for it! _Danke._

> Do you happen to be at EuroRust?
I am not deep into the Rust community (yet) and still learning.

**Comment by maxammann** [comment]
Are you sure you did not run a WebGL example in one of the experiments?

**Comment by maxammann** [comment]
The reason why I'm asking is that having a different FPS count seems impossible if both examples you executed are WebGPU. However I can confirm that at least the multithreading example is broken.

**Comment by mxzinke** [comment]
Sorry, the title of the issue was wrong, I meant WebGL.

With Firefox 131.0.3 the issue seams to be fixed. I think it is some related to https://bugzilla.mozilla.org/show_bug.cgi?id=1922278

Just tried it and all fine. Looking forward for further development in this project.
