### ISSUE TITLE
Add a section about contributors to README.md

### ISSUE THREAD

**Issue by maxammann** [maplibre/maplibre-rs#59]
We should mention all the awesome people who make maplibre-rs possible!

## 🤔 Expected Behavior

We should link to twitter/matrix/github profiles. Ideally we would mention roles attached to people who regularly contribute.

There should be an somewhat automatic way to update the contributors.

## 💁 Possible Solution
We could use something like that: https://github.com/all-contributors/all-contributors/blob/master/README.md

**Comment by neimsaci** [comment]
Ok, can you assign me?

**Comment by maxammann** [comment]
Closing for now, as the projet is just being revived after I was inactive in MapLibre for a while :P
