### ISSUE TITLE
Create a struct for `ZoomLevel`

### ISSUE THREAD

**Issue by Drabble** [maplibre/maplibre-rs#95]
We probably should add a struct for `ZoomLevel`.

_Originally posted by @maxammann in https://github.com/maplibre/maplibre-rs/pull/87#discussion_r867936765_

## 🤔 Expected Behavior

`Zoom` is a f64 which represents the current zoom on the map. It needs to be a floating number because we want to be able to zoom smoothly on the map.

`ZoomLevel` is a u8 which represents the level of a tile within the map's quad tree. `ZoomLevel` 0 would be one tile that contains the entire map, `ZoomLevel` 1 would be a part of the map if it was split in 4, etc. 

We can derive the current `ZoomLevel` from the `Zoom` using the constant `ZOOM_BOUNDS` defined in the `coords.rs` file.

## 😯 Current Behavior

Currently `ZoomLevel` is always stored as a u8 directly.

## 💁 Possible Solution

We should create a custom type or a struct to store the zoom level.

## 🔦 Context

It would make the code easier to read.

## 💻 Examples

The function below could be changed from:

```rust
pub fn scale_to_zoom_level(&self, z: u8) -> f64
````
to:

```rust
pub fn scale_to_zoom_level(&self, z: ZoomLevel) -> f64
```

**Comment by ybiletskyi** [comment]
I'll try to pick up this issue. Can any one assign it to me?

**Comment by maxammann** [comment]
Sure! If you have any questions feel free to contact me on matrix

**Comment by maxammann** [comment]
I think both "zoomes" are conceptionally quite different and their documentation will also differ. While zoom is a property of the "viewport", the zoom level is a property of a tile (like you said).
Accepting a f32 for a function which expects the zoom level of the currently displayed layer out of tiles probably does not make sense.

**Comment by ybiletskyi** [comment]
Should this be a type alias instead of creating a new struct? If it's just need for improving code reading.

**Comment by maxammann** [comment]
I think a new struct makes sense, so we can actually define functions on a ZoomLevel and make sure people understand what this u8 means.
