### ISSUE TITLE
Improve Overall Architecture

### ISSUE THREAD

**Issue by maxammann** [maplibre/maplibre-rs#96]
## 🤔 Expected Behavior

- `MapState` contains only the state such as zoom, coordinates. And maybe some utility functions to retrieve the tiles in a bbox.
- `MapContext` stores the `MapState`. It could possibly store multiple map states if we need multiple maps at the same time? It also stores the scheduler, http client, tilecache and other utilities.
- `MapRenderer` would access a `MapContext` and provide functions such as `prepare_render()`, `update_and_redraw()` and store the `render_state`.

We also want to support (maybe):

* headless rendering
* Using different renderers
* etc.

**Comment by Drabble** [comment]
A quick thought:

- `MapRenderer` - could have multiple types. One called `WinitMapRenderer`, one called `HeadlessMapRenderer`. 
- `WinitMapRenderer` - would handle the Winit event loop with inputs to update the `MapState`.
- `HeadlessMapRenderer` - would just start the whole process and render it to an image.

I have made a vague diagram of that:

![Architecture diagram](https://user-images.githubusercontent.com/3996615/168062522-07373c85-1646-45e0-aa13-3f24af5aec05.png)

**Comment by maxammann** [comment]
That definitely makes sense! We will see how we can split the behaviors because Rust does not use inheritance. 

* There probably wont be a `WinitMapRenderer`, but just a winit driver which ignites the rendering and keeps it going.
* Headless will be similar to the winit driver, exept that it does not kick off the rendering loop, but does only one iteration after data loading is finished
* There will be a wgpu based render, and possible more. Ther could be a vulkan-only renderer for instance.

**Comment by maxammann** [comment]
After thinking a bit more: There are probably 3 core modules of maplinre-rs:

* data loading pipeline (incl. tesselation)
* renderer
* window and surface handler

Modules like input handling also exist but are not core.

**Comment by maxammann** [comment]
Kind of done now :)
